stages:
  - test

image: php:8.4

services:
  - name: postgres:15
    alias: postgres

variables:
  APP_ENV: testing
  APP_DEBUG: "true"
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: 5432
  DB_DATABASE: laravel_test
  DB_USERNAME: laravel
  DB_PASSWORD: secret
  POSTGRES_DB: laravel_test
  POSTGRES_USER: laravel
  POSTGRES_PASSWORD: secret
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync

test_laravel:
  stage: test

  before_script:
    - apt-get update && apt-get install -y git unzip curl libzip-dev libpq-dev postgresql-client
    - docker-php-ext-install pdo_pgsql zip
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - cp .env.example .env
    - echo "APP_ENV=testing" >> .env
    - echo "DB_CONNECTION=pgsql" >> .env
    - echo "DB_HOST=postgres" >> .env
    - echo "DB_PORT=5432" >> .env
    - echo "DB_DATABASE=laravel_test" >> .env
    - echo "DB_USERNAME=laravel" >> .env
    - echo "DB_PASSWORD=secret" >> .env
    - php artisan key:generate
    - php artisan config:clear
    - until pg_isready -h postgres -p 5432 -U laravel; do echo "Waiting for PostgreSQL..."; sleep 2; done
    - printenv | grep DB_

  script:
    - php artisan migrate --force
    - php artisan test

  only:
    - main